"""update server root jobs table

Revision ID: 56ca5c0f11c4
Revises: 6a4ced57dff9
Create Date: 2024-04-27 13:06:46.757750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ca5c0f11c4'
down_revision: Union[str, None] = '6a4ced57dff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_root_jobs', sa.Column('locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_root_jobs', 'locked')
    # ### end Alembic commands ###
