"""add lock by field

Revision ID: 59a5e01a115b
Revises: 56ca5c0f11c4
Create Date: 2024-04-27 17:11:01.825324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a5e01a115b'
down_revision: Union[str, None] = '56ca5c0f11c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_root_jobs', sa.Column('locked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_root_jobs', 'locked_at')
    # ### end Alembic commands ###
