"""Initial migration

Revision ID: 75df73a890e1
Revises: 
Create Date: 2024-04-20 14:45:24.986613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75df73a890e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_root_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_server_root_jobs_id'), 'server_root_jobs', ['id'], unique=False)
    op.create_table('server_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ram', sa.Float(), nullable=True),
    sa.Column('cpu', sa.Float(), nullable=True),
    sa.Column('disk', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_usage_id'), 'server_usage', ['id'], unique=False)
    op.create_table('service_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ram', sa.Float(), nullable=True),
    sa.Column('cpu', sa.Float(), nullable=True),
    sa.Column('disk', sa.Float(), nullable=True),
    sa.Column('read', sa.Float(), nullable=True),
    sa.Column('write', sa.Float(), nullable=True),
    sa.Column('network_rx', sa.Float(), nullable=True),
    sa.Column('network_tx', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_usage_id'), 'service_usage', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_service_usage_id'), table_name='service_usage')
    op.drop_table('service_usage')
    op.drop_index(op.f('ix_server_usage_id'), table_name='server_usage')
    op.drop_table('server_usage')
    op.drop_index(op.f('ix_server_root_jobs_id'), table_name='server_root_jobs')
    op.drop_table('server_root_jobs')
    # ### end Alembic commands ###
